# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = true

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
    "https://raw.githubusercontent.com/peasoft/NoMoreWalls/refs/heads/master/snippets/nodes.meta.yml",
    "https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Clash",
    "https://raw.githubusercontent.com/qianlima8888/autoClashProxy/refs/heads/main/list.yaml"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = true
rename_pattern = "${COUNTRYCODE}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = true
# 代理节点池
pools = [
    "https://raw.githubusercontent.com/dongchengjie/airport/main/subs/merged/tested_within.yaml"
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "http://www.google.com/generate_204"
expected = 204
timeout = 500

# 带宽测速配置
[speed_test]
enabled = true
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 3000
