# 是否开启快速模式，快速模式下仅测试连通性
fast_mode = false

# 待测速的订阅节点
# 支持网络地址 https://xxx
# 支持本地地址（绝对地址）/User/xxx/xx.yml
# 支持单个订阅链接，ss://xxx
subs = [
    "https://raw.githubusercontent.com/dongchengjie/airport/main/subs/merged/tested_within.yaml",
    "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml",
    "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/refs/heads/main/meta.yaml",
    "https://raw.githubusercontent.com/wangyingbo/v2rayse_sub/refs/heads/main/wzdnzd_aggregator_sub/Clash"
]

# 是否重命名节点，打开后会使用 geoip 等方式进行代理真实 IP 和地理地址查询
rename_node = false
rename_pattern = "${COUNTRYCODE}"

# 是否需要加上代理池的节点一起筛选
need_add_pool = false
# 代理节点池
pools = [
]

# 测试分组大小
test_group_size = 50

# 连通性测试
[connect_test]
url = "https://www.cna.com.tw/"
#expected = 204
timeout = 400

# 带宽测速配置
[speed_test]
enabled = true
url = "https://speed.cloudflare.com/__down?bytes=104857600"
timeout = 2000
